-
where clause
--WHERE CLAUSE IS USED TO FILITER THE DATA 
--IT IS USED TO FILTRING THE DATA FROM TABLES
--IT IS USED ALOG WITH WHERE CLAUSE ONLY 

SELECT *FROM Customer WHERE ID=40; 
 SELECT *FROM Customer WHERE ID IN(20,40,30,50,12,56,34);

 --ODERBY CLAUSE OIS USED  TO SORTING DATA
  SELECT *FROM Customer ORDER BY CITY DESC
    SELECT *FROM Customer ORDER BY iD DESC
	TOP CLAUSE IS USED TO FETECHING DATA 
	SELECT TOP 20 *FROM CUSTOMER
	SELECT TOP 10 PERCENT  *FROM CUSTOMER


	-- GROUP BY 
	--GROUP BY ID USED TO GROUP SIMLAR DATA TYPES ONLY
	--IT IS USED ALONG WITH A  AGGREATIVE FUNCTIONS  

	SELECT SUM(UNITPRICE),ID  FROM [dbo].[Order_Iteam_Details] GROUP BY ID

	-ROLLUP AND CUBE 
--THIS ARE SPECIAL CLAUSES WHICH ARE USED TO CLACULATE SUB AND GRAND TOTAL 
--THIS CLAUSE ARE USED ALONG WITH GROUP BY ONLY
--ROLLUP WITH -SINGEL COLUMN 
--CUBE WITH -MULTI COLUMN

SELECT SUM(UNITPRICE)AS TUL, QUANTITY FROM Order_Iteam_Details GROUP BY ROLLUP(QUANTITY)

SELECT SUM(QUANTITY) AS TL,orderIteam FROM Order_Iteam_Details GROUP BY CUBE(orderIteam)


