CREATE APPLICATION ROLE [DBSrikanthEquiJoins]
	WITH PASSWORD = 'q=qooEyth|{Nb>lai8ekdwgrmsFT7_&#$!~<`gzdZoe`{ut#'
--EQUI JOIN
--JOINS CANBE DONE WITH WHERE KEYWORD ONLY
--WHEN WE RETRIVE THE DATA FROM TWO OR MORE TABLES BASED ON EQUALITY CONDITION IS CALLED AS EQUI JOIN
--IT IS ALWAYS RIGHT TO LEFT 
USE JOINS
--WAQ D,FIRSTNAME,ORDERITEAM,UNITPRICE FROM CUSTOMER,[Order_Iteam_Details] AND ID =23

SELECT C.ID,FIRSTNAME,ORDERITEAM,UNITPRICE FROM CUSTOMER AS C,[Order_Iteam_Details] AS O WHERE C.ID=O.ID;

SELECT C.ID,FIRSTNAME,ORDERITEAM,UNITPRICE FROM CUSTOMER AS C,[Order_Iteam_Details] AS O WHERE C.ID=O.ID AND C.ID=23

SELECT C.ID,FIRSTNAME,QUANTITY FROM Customer AS C ,Order_Iteam_Details AS O WHERE C.ID=O.ID AND FIRSTNAME='THOMAS' 

SELECT * FROM CUSTOMER 
SELECT * FROM Order_Iteam_Details

SELECT SUM(UNITPRICE) AS [TOTAL PRICE],CITY FROM Order_Iteam_Details AS O,CUSTOMER AS C WHERE C.ID=O.ID GROUP BY CITY;


 SELECT SUM(UNITPRICE) AS TOTALPRICE ,COUNTRY FROM Order_Iteam_Details AS O,CUSTOMER AS C WHERE C.ID=O.ID GROUP BY COUNTRY